services:
  - type: web
    name: veltech-hotel
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: veltech_super_secret_key_change_this
      - key: NODE_ENV
        value: production
